### ISSUE TITLE
The "minecraft:sell_potion_holding_item" factory is documented incorrectly

### ISSUE THREAD

**Issue by ppblitto** [aws404/SimpleJsonVillagerTrades#1]
Hello. I'm trying to use this trade offer factory, but the trades don't appear in the villager's ui. I'm following every step of the wiki.

This is what I wrote according with the trade offer factory options in the wiki

`{
"type": "minecraft:set_potion_holding_item", "price": 3, "second_count": 5, "arrow": "minecraft_arrow", "sell_count": 5, "tipped_arrow": "minecraft:tipped_arrow",  "max_uses": 12, "experience": 10
}`

Note that in the example, the code seems simpler:
![image](https://user-images.githubusercontent.com/57157437/153331955-6bab044f-118e-4819-b553-9a3dd8d74a2a.png)
I tried using this way too, but nothing changed.

**Comment by aws404** [comment]
Thankyou for picking this up, it was an error in the docs.
The `type` should be `minecraft:sell_potion_holding_item` (sell rather than set).

**Comment by ppblitto** [comment]
Thank you!
