### ISSUE TITLE
Incompatible with 1.18.2

### ISSUE THREAD

**Issue by ChrysanthCow** [aws404/SimpleJsonVillagerTrades#2]
*Data changes go brrr*

Hi, I'm just writing this to hopefully reach out to you about updating this mod to 1.18.2 at some stage.

**Comment by ChrysanthCow** [comment]
If you'd like I could take a look at PRing 1.18.2 compatibility tho I get if you want to do it yourself.

**Comment by aws404** [comment]
Working on it now!

**Comment by aws404** [comment]
Been some big refactoring, only 1 breaking change from the datapack side, being that `minecraft:sell_map` is now tag based and requires you to specify the translation key.
Will publish update shortly.
